### ISSUE TITLE
Allow smaller values for MIN NOTE DURATION

### ISSUE THREAD

**Issue by mslinn** [DamRsn/NeuralNote#100]
Currently, the minimum possible value of MIN NOTE DURATION is 35 ms for the Standalone program. This is a much longer duration than the 3 ms minimum possible with the parent project, Basic Pitch. A lower value would be helpful - all the way down to 3 ms if possible.

**Comment by DamRsn** [comment]
Hi,

Thanks for reporting this.

I think the value of 3 ms in BasicPitch is incorrect. The unit is not ms but frames. A basic pitch frame is 11.6 ms (256 samples at 22050 Hz). So the 3 ms on the basic pitch website corresponds to the 35 ms in NeuralNote. 

I discovered that issue while going through their code to implement NeuralNote, but I forgot to report it to them.
