### ISSUE TITLE
hey i just scanned neuralnote in virustotal.com and there was something malliscous "Win.MxResIcn.Heur.Gen" false positive or not?

### ISSUE THREAD

**Issue by yabayabado** [DamRsn/NeuralNote#107]

**Comment by DamRsn** [comment]
Hi, thanks for pointing this out.

Honestly, I'm not sure what "Win.MxResIcn.Heur.Gen" means exactly, but it looks like one of those heuristic detections that can sometimes flag harmless stuff as malware. It's probably a false positive.
