### ISSUE TITLE
Proposal for realtime audio

### ISSUE THREAD

**Issue by geraldmwangi** [DamRsn/NeuralNote#108]
Hi. I am the developer of GuitarMidi-LV2 (https://github.com/geraldmwangi/GuitarMidi-LV2).
GuitarMidi does guitar to midi via a bank of elliptic cauer filters instead of CQT. 
 The filterbank is divided into harmonic groups.
This allows near realtime tracking of the lower E string notes at buffersize 256 samples at 48khz,  using the differences in the overtones which are identical to the fundamentals, as well as the fundamentals themselves

The plugin does monophonic and polyphonic tracking, the later is not accurate and produces false positive midi notes from the overtones of the strings played. In monophonic mode the plugin works quite well, although not 100%.

I am researching neural nets since I would like to use the output of the harmonic filterbank as the input of a neural net to reduce the false positives from the overtones.

Maybe we could join forces and integrate Elliptic Cauer Filters into NeuralNote for realtime transcription?

**Comment by DamRsn** [comment]
Hi, sorry for the very late response!

Unfortunately I don't have the bandwidth to do research on real-time transcription at the moment. If you have something already working and pretty solid, I could have a look and check if it's worth integrating in NeuralNote (but I'm not sure to even have the time to work on the integration unfortunately). 

Also something that might be of interest for you if you're researching neural nets: Spotify recently released their training code for basic-pitch, so you could use that as a starting point and tweak the features.

**Comment by geraldmwangi** [comment]
Hi. Thanks for the answer. Ive looked at basic pitch, however it is not realtime and that's the goal of my plugin. You can already test my plugin, if you like, I release Debian packages for it
