### ISSUE TITLE
export data in other formats

### ISSUE THREAD

**Issue by edellaq** [DamRsn/NeuralNote#110]
Hello,
would it be possible to have an export option for MIDI data in JSON format?
I'm using at the moment NN to obtain a midi file from a solo guitar audio file, then I go to this website
[https://www.visipiano.com/midi-to-json-converter/](url)
to obtain a JSON file that I can use for a javascript SPA I'm working on.
Neural Note pitch to MIDI works pretty well, especially for single instruments, like a solo guitar.
Would be great to have directly also the data in JSON format.

the goal is to arrive to this:
[https://www.youtube.com/watch?v=GyLWbH9ii_Q](url)
without getting mad with MIDI guitar pickups, etc... (that's how I made the video)
and NN is a Godsend in this regard.

**Comment by DamRsn** [comment]
Hi, 

I don't plan on adding json export option as the NeuralNote plugin/app is not meant to be used in this context. If you wish to integrate NeuralNote transcription capabilities in a javascript SPA pipeline, I suggest you use directly BasicPitch, [here's the typescript version open source](https://github.com/spotify/basic-pitch-ts) and then find a lib that can do the conversion to json automatically.
