### ISSUE TITLE
Minimum note duration

### ISSUE THREAD

**Issue by SolfaMode** [DamRsn/NeuralNote#111]
The miminum note duration setting might not work as expected.
Problem may the following line in BasicPitch::setParameters.
    mParams.minNoteLength = static_cast<int>(std::round(inMinNoteDurationMs * FFT_HOP / BASIC_PITCH_SAMPLE_RATE));
From how it is used in Notes.cpp minNoteLength is the number of frames in the posteriograms.
In BasicPitch training there are 172.0 * 22050.0 / 43844.0 posteriogram frames per second.
So line should be instead:
    mParams.minNoteLength = static_cast<int>(std::round(params.minNoteDurationMs / 1000.0 * 172.0 * 22050.0 / 43844.0));

**Comment by DamRsn** [comment]
Hi,

Thanks for catching that. I think the fix would look more like: `mParams.minNoteLength = static_cast<int>(std::round(inMinNoteDurationMs / 1000.0 * FFT_HOP / BASIC_PITCH_SAMPLE_RATE));
`
 
 The frame rate in basic pitch being `FFT_HOP / BASIC_PITCH_SAMPLE_RATE` (`256 / 22050`)
 
 I'll fix it soon.
