### ISSUE TITLE
Failed to build the source corde

### ISSUE THREAD

**Issue by Sakura-Hydrangea** [DamRsn/NeuralNote#117]
![屏幕截图 2024-09-06 223542](https://github.com/user-attachments/assets/a2bf0523-db0e-4805-a6da-c7f3481d9627)
I tried several times but still failed to solve this problem.Are there any possble reasons and solutions.
Thank you dearly!

**Comment by DamRsn** [comment]
Hi,

I've never encountered these kind of errors. Did you build onnxruntime static lib successfully before trying to build NeuralNote?

What compiler are you using?
