### ISSUE TITLE
I'm getting this error on MPC

### ISSUE THREAD

**Issue by bentorukmakto** [DamRsn/NeuralNote#138]
![neu ekran](https://github.com/user-attachments/assets/424d7eec-5b3d-4c19-8408-7126a5575554)

Hello, 

I get this error when using NeuralNote with element vst in Mpc software. I'm sure the works I used are mp3.

**Comment by DamRsn** [comment]
Hey, 

Could you try with the standalone version with the same file and check if the same error occurs?

**Comment by bentorukmakto** [comment]
![vstHost standalone](https://github.com/user-attachments/assets/badd6139-a5ca-416a-a7e7-336c2e05e46b)

I tried running it as standalone with VstHost, still the same problem.

**Comment by DamRsn** [comment]
I meant using the standalone NeuralNote application (not the VST plugin). You don't need a host to use it. You can choose to install it in the installer if you don't have it already. 

Also, is it possible for you to send me the mp3 file? So I can try to reproduce the issue.

**Comment by bentorukmakto** [comment]
I managed to get wav. working. Thank you
