### ISSUE TITLE
3 Minute Limit Workaround?

### ISSUE THREAD

**Issue by solipsystems** [DamRsn/NeuralNote#28]
Thanks for porting this. Much appreciated.

Is there any way to get around the 3 minute maximum for inputs?

**Comment by DamRsn** [comment]
Hi! 
Currently no, but we could increase it as this value quite arbitrary. 

If you're building from source you can easily modify it by setting `mMaxDuration` in `NeuralNote/PluginSources/PluginProcessor.h` to suit your need.

**Comment by LuluViBritannia** [comment]
I second that! The 3 minutes limit is frustrating, especially when your song is 3m01 long, lol.
Could this limit be removed altogether? There are songs that are longer than 10 minutes.
For now, the easy workaround is to cut the original audio in two and work with each part.

**Comment by DamRsn** [comment]
Hi, Yes I'm currently working on it in #38. The limit will be removed both for recorded audio and dropped files. 

This specific point should be ready soon but I want to add more improvements/features before the next release that is scheduled for sometime in July/August

**Comment by DamRsn** [comment]
There is no 3 minute limit anymore.
