### ISSUE TITLE
CLAP plugin with live output or MPE note expressions

### ISSUE THREAD

**Issue by Yzrsah** [DamRsn/NeuralNote#29]
Thank you for making NeuralNote

It would be really great to have access to polyphonic pitch bend expressions on the transcribed notes.

CLAP can do it with CLAP_NOTE_EXPRESSION_TUNING

Edit: This would require live output, so exporting MIDI with MPE note expressions would be needed instead

**Comment by DamRsn** [comment]
Hi!

Thanks for pointing this out, this is definitely something I'd like to add to NeuralNote. 

I don't plan on adding CLAP support at the moment, and as you say, NeuralNote does not do live output. So MPE export seems to be the way to go, although I don't know a lot about it. 

It would be great if someone could help contributing on this one! 🙂
