### ISSUE TITLE
Be able to play transcription without having to export midi

### ISSUE THREAD

**Issue by DamRsn** [DamRsn/NeuralNote#30]
Either implement a simple synth inside NeuralNote, or find an elegant way to route the transcribed MIDI to another synth.

Add `Play` and `Stop` buttons, a clickable playhead and a mixer for levels of the source audio and the synthesized transcription.

This would help to adjust the parameters to get the best transcription possible.

**Comment by seoulrebel** [comment]
Just wanted to say thank you for your time and effort. Hoping the addition of this feature is upcoming with the next update.
