### ISSUE TITLE
Windows/protools

### ISSUE THREAD

**Issue by TeamBirdy** [DamRsn/NeuralNote#32]
I'm really eager and excited to try this tool but I'm using windows and pro tools, I do not understand how to get this working. I put the VST3 file into its appropriate folder but this is not recognized in my DAW. Someone please helppp!!!

**Comment by DamRsn** [comment]
Hi,

As far as I know Protools does not support VST plugins but only AAX ones, which we don't support.

It seems there exist some hacky ways to get VSTs working/interact with Protools, you might want to look for those things online!
