### ISSUE TITLE
MP3 and OGG support

### ISSUE THREAD

**Issue by DamRsn** [DamRsn/NeuralNote#37]
Support dropping mp3 files

**Comment by RustoMCSpit** [comment]
does this support other formats too like .ogg ?

**Comment by RustoMCSpit** [comment]
> No ogg is not supported for the moment.
edit the title of this issue to say 'Multi-format support' then

**Comment by DamRsn** [comment]
Support for `mp3` and `.ogg` file is added in #60. It needs to be tested on Windows before merging.

**Comment by DamRsn** [comment]
#60 has been merged, `.mp3` and `.ogg` are now supported.

**Comment by RustoMCSpit** [comment]
> #60 has been merged, `.mp3` and `.ogg` are now supported.

.opus?

**Comment by RustoMCSpit** [comment]
> #60 has been merged, `.mp3` and `.ogg` are now supported.

any update on .opus support?
