### ISSUE TITLE
Linux/Wine support

### ISSUE THREAD

**Issue by mickaelistria** [DamRsn/NeuralNote#40]
I'm trying to try NeuralNote on Linux and wasn't successful when trying to build it (seems to require some dependencies to become Linux-compatible) nor when using yabridge+Wine, error is
```
22:30:29 [NeuralNote-ACDFPWZr] Initializing yabridge version 5.0.5
22:30:29 [NeuralNote-ACDFPWZr] library:       '/lib64/libyabridge-vst3.so'
22:30:29 [NeuralNote-ACDFPWZr] host:          '/usr/bin/yabridge-host.exe'
22:30:29 [NeuralNote-ACDFPWZr] plugin:        '/home/mistria/.wine/drive_c/Program Files/Common Files/VST3/NeuralNote.vst3'
22:30:29 [NeuralNote-ACDFPWZr] plugin type:   'VST3'
22:30:29 [NeuralNote-ACDFPWZr] realtime:      'no'
22:30:29 [NeuralNote-ACDFPWZr] memlock limit: '8388608 bytes, see below'
22:30:29 [NeuralNote-ACDFPWZr] 
22:30:29 [NeuralNote-ACDFPWZr]    With a low memory locking limit, yabridge may not be
22:30:29 [NeuralNote-ACDFPWZr]    be able to lock its shared memory audio buffers into
22:30:29 [NeuralNote-ACDFPWZr]    main memory. Performance may be degraded until you fix 
22:30:29 [NeuralNote-ACDFPWZr]    this. Check the readme for instructions on how to do that.
22:30:29 [NeuralNote-ACDFPWZr] 
22:30:29 [NeuralNote-ACDFPWZr] sockets:       '/run/user/1000/yabridge-NeuralNote-ACDFPWZr'
22:30:29 [NeuralNote-ACDFPWZr] wine prefix:   '/home/mistria/.wine'
22:30:29 [NeuralNote-ACDFPWZr] wine version:  '8.11 (Staging)'
22:30:29 [NeuralNote-ACDFPWZr] 
22:30:29 [NeuralNote-ACDFPWZr] config from:   '<defaults>'
22:30:29 [NeuralNote-ACDFPWZr] hosting mode:  'individually, 64-bit'
22:30:29 [NeuralNote-ACDFPWZr] other options: '<none>'
22:30:29 [NeuralNote-ACDFPWZr] 
22:30:29 [NeuralNote-ACDFPWZr] Enabled features:
22:30:29 [NeuralNote-ACDFPWZr] - bitbridge support
22:30:29 [NeuralNote-ACDFPWZr] - CLAP support
22:30:29 [NeuralNote-ACDFPWZr] - VST3 support
22:30:29 [NeuralNote-ACDFPWZr] 
22:30:29 [NeuralNote-ACDFPWZr] [Wine STDERR] Initializing yabridge host version 5.0.5
22:30:29 [NeuralNote-ACDFPWZr] [Wine STDERR] Preparing to load VST3 plugin at '/home/mistria/.wine/drive_c/Program Files/Common Files/VST3/NeuralNote.vst3'
22:30:30 [NeuralNote-ACDFPWZr] [Wine STDERR] Finished initializing '/home/mistria/.wine/drive_c/Program Files/Common Files/VST3/NeuralNote.vst3'
22:30:30 [NeuralNote-ACDFPWZr] [Wine STDERR] 0228:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000180808179, 46) stub
22:30:30 [NeuralNote-ACDFPWZr] [Wine STDERR] 0238:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000000001AAFE10
```
Can you please provide hints about the best direction to make progress with using NeuralNote on Linux?

**Comment by DamRsn** [comment]
When building JUCE apps or plugins on Linux, you need to have some dependencies installed. Everything is [documented here](https://github.com/juce-framework/JUCE/blob/master/docs/Linux%20Dependencies.md).

Concerning the yaybridge+Wine, I'm not familiar with those tools so I really don't know.

**Comment by Settyness** [comment]
I didn't even attempt a build, but I did successfully load the plugin -- and it is working -- with `yabridge 5.0.5` on Arch Linux `2023.07.22`.

    PluginHost: Reading VST 3 plugin metadata for /mnt/prod/Audio/Plugins/Yabridge/DamRsn/NeuralNote.vst3
    19:14:19 [NeuralNote-6COfgklx] Initializing yabridge version 5.0.5
    19:14:19 [NeuralNote-6COfgklx] library:       '/usr/lib/libyabridge-vst3.so'
    19:14:19 [NeuralNote-6COfgklx] host:          '/usr/bin/yabridge-host.exe'
    19:14:19 [NeuralNote-6COfgklx] plugin:        '/home/settyness/.winevst/drive_c/users/settyness/Yabridge/DamRsn/NeuralNote.vst3'
    19:14:19 [NeuralNote-6COfgklx] plugin type:   'VST3'
    19:14:19 [NeuralNote-6COfgklx] realtime:      'yes'
    19:14:19 [NeuralNote-6COfgklx] sockets:       '/run/user/1000/yabridge-NeuralNote-6COfgklx'
    19:14:19 [NeuralNote-6COfgklx] wine prefix:   '/home/settyness/.winevst'
    19:14:19 [NeuralNote-6COfgklx] wine version:  '8.12 (Staging)'
    19:14:19 [NeuralNote-6COfgklx] 
    19:14:19 [NeuralNote-6COfgklx] config from:   '<defaults>'
    19:14:19 [NeuralNote-6COfgklx] hosting mode:  'individually, 64-bit'
    19:14:19 [NeuralNote-6COfgklx] other options: '<none>'
    19:14:19 [NeuralNote-6COfgklx] 
    19:14:19 [NeuralNote-6COfgklx] Enabled features:
    19:14:19 [NeuralNote-6COfgklx] - bitbridge support
    19:14:19 [NeuralNote-6COfgklx] - CLAP support
    19:14:19 [NeuralNote-6COfgklx] - VST3 support
    19:14:19 [NeuralNote-6COfgklx] 
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 8.12 is a testing version containing experimental patches.
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:19 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] 0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] Initializing yabridge host version 5.0.5
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] Preparing to load VST3 plugin at '/home/settyness/.winevst/drive_c/users/settyness/Yabridge/DamRsn/NeuralNote.vst3'
    19:14:20 [NeuralNote-6COfgklx] [Wine STDERR] Finished initializing '/home/settyness/.winevst/drive_c/users/settyness/Yabridge/DamRsn/NeuralNote.vst3'

Only difference I spot is the `wine-staging` version, which has been updated since your OP.  Maybe rebridge and try again? Sorry I can't add much, just trying to be helpful and provide another voice for GNU/Linux.

**Comment by mickaelistria** [comment]
I managed to get it working over yabridge a few days ago. I suspect my issues were more in wine or carla. I think we can close it for the moment as I personally don't need it any more.
