### ISSUE TITLE
more scales / modes supported

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#46]

**Comment by DamRsn** [comment]
Yes some more scales / modes could be added easily. Could you list the new scales that you'd like to see added to `Chromatic`, `Major`, `Minor` that are already in NeuralNote?

**Comment by RustoMCSpit** [comment]
> Yes some more scales / modes could be added easily. Could you list the new scales that you'd like to see added to `Chromatic`, `Major`, `Minor` that are already in NeuralNote?

melodic minor, harmonic minor, blues, all the modes, https://en.m.wikipedia.org/wiki/Category:Musical_scales

**Comment by RustoMCSpit** [comment]
auto detection of scales would be cool
