### ISSUE TITLE
built in help manual

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#47]

**Comment by DamRsn** [comment]
I don't plan on creating a built-in help manual. When the new features will be developed, I'll probably make a video where I explain the different options and how to use them.

**Comment by RustoMCSpit** [comment]
> I don't plan on creating a built-in help manual. When the new features will be developed, I'll probably make a video where I explain the different options and how to use them.

doesnt seem practical when you cpuld just have a few lines of text
