### ISSUE TITLE
tuner mode

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#48]

**Comment by DamRsn** [comment]
Can you be more specific?

**Comment by RustoMCSpit** [comment]
> Can you be more specific?

app acts like a tuner and has a GUI for it?
also off the rails here but as it's polyphonic could it tune six strings at once

**Comment by DamRsn** [comment]
BasicPitch does not have a high enough frequency resolution to be used as a tuner (only 3 bins per semitone if using pitch bend info). Plus there are already many good tuners out there.
