### ISSUE TITLE
take features from: https://www.youtube.com/watch?v=ajN_fWja_84&list=PLBbMkfXvxdzpj_tizshI6z07nPgqeHZLp&index=1

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#50]
https://www.youtube.com/watch?v=ajN_fWja_84&list=PLBbMkfXvxdzpj_tizshI6z07nPgqeHZLp&index=1

**Comment by DamRsn** [comment]
Can you be more specific about what features you'd like to see in NeuralNote?

**Comment by RustoMCSpit** [comment]
> Can you be more specific about what features you'd like to see in NeuralNote?

i kept it open so you could see whats viable cause idk

**Comment by DamRsn** [comment]
Closed as the feature request was not detailed enough.
