### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#51]
if so, add to f-droid

**Comment by RustoMCSpit** [comment]
and make a material theme and have custom monochrome icon theming support

**Comment by DamRsn** [comment]
I don't plan to add Andoird support. A mobile app would be too different from the plugin/desktop app that NeuralNote is.

**Comment by RustoMCSpit** [comment]
> A mobile app would be too different from the plugin/desktop app that NeuralNote is.

i mean, not really, i know some android devs i can ask them to look at how hard it would be to port this /if thry wanted to if you want
