### ISSUE TITLE
GUI improvement

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#52]
It's a project to improve the design of open source apps. So it provides resources, connects designers (like OP) with engineers/projects, spreads awareness etc.

https://opensourcedesign.net/jobs/ apply the project here!!

**Comment by DamRsn** [comment]
Thanks for the resource, but I'm already working with a designer on NeuralNote. Some more functionalities are now under development and the GUI will be adapted accordingly.

**Comment by RustoMCSpit** [comment]
> Thanks for the resource, but I'm already working with a designer on NeuralNote. Some more functionalities are now under development and the GUI will be adapted accordingly.

are they going to add customisable themes and the ability to change the piano's look
