### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by HimoriK** [DamRsn/NeuralNote#59]
Is it possible to get a web/pip install version of this so it's not constrained to a DAW?

**Comment by DamRsn** [comment]
Hi, 

I'm not sure of what you mean. But if you want something not constrained to a DAW, you can use the standalone app (Mac or Windows Standalone [here](https://github.com/DamRsn/NeuralNote/releases/tag/v0.0.1)). 

Or if you want a web interface, you can go on the [BasicPitch website](https://basicpitch.spotify.com/) directly.

**Comment by HimoriK** [comment]
Thank you!
