### ISSUE TITLE
.opus support and other formats

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#70]

**Comment by RustoMCSpit** [comment]
FLAC (Free Lossless Audio Codec)
    Homepage: https://xiph.org/flac/

    WavPack
    Homepage: http://www.wavpack.com/

    Opus
    Homepage: https://opus-codec.org/

    Vorbis
    Homepage: https://xiph.org/vorbis/

    Speex
    Homepage: https://speex.org/

    ALAC (Apple Lossless Audio Codec)
    Homepage: https://alac.macosforge.org/

    TAK (Tom's Lossless Audio Kompressor)
    Homepage: http://www.thbeck.de/Tak/Tak.html

    LA (Lossless Audio)
    Homepage: http://www.lossless-audio.com/

    APE (Monkey's Audio)
    Homepage: https://www.monkeysaudio.com/

**Comment by RustoMCSpit** [comment]
FLAC (Free Lossless Audio Codec)
Homepage: https://xiph.org/flac/

WavPack
Homepage: http://www.wavpack.com/

Opus
Homepage: https://opus-codec.org/

Vorbis
Homepage: https://xiph.org/vorbis/

Speex
Homepage: https://speex.org/

ALAC (Apple Lossless Audio Codec)
Homepage: https://alac.macosforge.org/

TAK (Tom's Lossless Audio Kompressor)
Homepage: http://www.thbeck.de/Tak/Tak.html

LA (Lossless Audio)
Homepage: http://www.lossless-audio.com/

APE (Monkey's Audio)
Homepage: https://www.monkeysaudio.com/

**Comment by DamRsn** [comment]
I don't plan on supporting every audio format in the world. I think the set of supported format (wav, mp3, flac, aiff & ogg vorbis) is broad enough so that no one I blocked from using NeuralNote because of that.

**Comment by RustoMCSpit** [comment]
> I don't plan on supporting every audio format in the world. I think the set of supported formats (wav, mp3, flac, aiff & ogg vorbis) is broad enough so that no one I blocked from using NeuralNote because of that.

can we at least have .opus as .opus is the successor to .ogg and is more efficient. Both Vorbis and Opus have better audio quality and smaller file size than MP3.
