### ISSUE TITLE
have a tuner built-in

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#73]
theres plenty of foss tuners. it would be useful if one was built-in so people doing vocals can see how off they are in real-time and correct themselves

**Comment by DamRsn** [comment]
> theres plenty of foss tuners. it would be useful if one was built-in so people doing vocals can see how off they are in real-time and correct themselves

I don't plan on adding a tuner. And the algorithm does not work in real time.
