### ISSUE TITLE
offer more background choices

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#74]
or allow the user to input hexs to decide the colors of components.

the rainbow hurts my eyes man

**Comment by DamRsn** [comment]
> or allow the user to input hexs to decide the colors of components.
> 
> 
> 
> the rainbow hurts my eyes man

I don't plan on supporting other backgrounds/colors.

**Comment by RustoMCSpit** [comment]
> I don't plan on supporting other backgrounds/colors.
can you at least merge the ones i made and tried to pull request and allow me to add in new backgrounds?
