### ISSUE TITLE
How can I use the built files in Xcode

### ISSUE THREAD

**Issue by KittenYang** [DamRsn/NeuralNote#84]
<img width="478" alt="截屏2023-10-28 15 16 00" src="https://github.com/DamRsn/NeuralNote/assets/5517281/991d18c8-e6d5-46ed-8b93-5d8d32749e82">

I built those output, any ideas how to use it in Xcode? Thanks indeed~

**Comment by DamRsn** [comment]
I think that if you wish to work on the project from XCode, you need to change the cmake generator with -G option and set it to Xcode.

You can see here: https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html

**Comment by KittenYang** [comment]
Thanks bro, I'll check it

**Comment by KittenYang** [comment]
I finally generate the Xcode project, and it build succeed with .a static library. But there is no any header files. Do you know which header file should I use to convert a .mp3 file to MIDI file?
<img width="671" alt="截屏2023-10-30 17 38 54" src="https://github.com/DamRsn/NeuralNote/assets/5517281/45702e11-d0de-4739-83c3-53cd57ebe711">
<img width="410" alt="截屏2023-10-30 17 39 02" src="https://github.com/DamRsn/NeuralNote/assets/5517281/7c1ba1b4-9c71-4ebc-8a6a-4e29d7dc43f4">

**Comment by DamRsn** [comment]
To convert an audio file to midi, you need to build the application (the standalone target for example, so you don't need a DAW). After that you will be able to run the application and load the audio file to get the midi results.

You can also simply install the [latest release](https://github.com/DamRsn/NeuralNote/releases/tag/v0.1.0) for Mac.

**Comment by KittenYang** [comment]
> To convert an audio file to midi, you need to build the application (the standalone target for example, so you don't need a DAW). After that you will be able to run the application and load the audio file to get the midi results.
> 
> You can also simply install the [latest release](https://github.com/DamRsn/NeuralNote/releases/tag/v0.1.0) for Mac.

How can I minimize the integration of this mp3-to-midi function into my own application? as I may not need the UI component.

**Comment by DamRsn** [comment]
Oh I see, you will need to add different things from NeuralNote into your project, and compile those with your application. 

The things you need to add are:
- All the code in `Lib/Model`
- The onnx model as BinaryData (or you could change the session initialization in `Features.cpp` to load the model from a file instead). 
- RTNeural
- ONNXRuntime, either as a dynamic library (simpler, binaries provided on onnxruntime gh), or as a static library and you'll need to follow the instruction given for that in the readme.

Hope that helps

**Comment by KittenYang** [comment]
@DamRsn Thanks mate! I'll try those instructions.
