### ISSUE TITLE
could not load the audio file

### ISSUE THREAD

**Issue by noodlehaha666** [DamRsn/NeuralNote#87]
![微信图片_20231110015722](https://github.com/DamRsn/NeuralNote/assets/133321416/70fbb680-73ec-4c19-86f9-03fb8d9b4dce)
i tried to upload files as .wav and .mp3 both in standalone and daw shows this, please help~~

**Comment by DamRsn** [comment]
Hi, 

Are you on Mac or Windows? And on which version? 

Could you also send me a file for which it did not work? 

Thanks

**Comment by noodlehaha666** [comment]
it's windows and v0.1.0
.mp3 and .wac file attachment is not supported :( can i get your email address?
much appreciated!

**Comment by noodlehaha666** [comment]
win 10

**Comment by noodlehaha666** [comment]
I am using Win10 and it worked with flac file! Thank you
________________________________
发件人: Damien Ronssin ***@***.***>
发送时间: 2023年11月9日 15:12
收件人: DamRsn/NeuralNote ***@***.***>
抄送: noodlehaha666 ***@***.***>; Author ***@***.***>
主题: Re: [DamRsn/NeuralNote] could not load the audio file (Issue #87)


Hi,

Are you on Mac or Windows? And on which version?

Could you also send me a file for which it did not work?

Thanks

―

**Comment by revaraver** [comment]
I encountered the same problem and solved it. The key point is that there cannot be special characters in the file name. You may also need to confirm that there are no special characters in the file path. Maybe it will help:)

**Comment by noodlehaha666** [comment]
appreciate your help!

Miaoyan Huang

On 14 Jan 2024, at 17:55, revar ***@***.***> wrote:

﻿

I encountered the same problem and solved it. The key point is that there cannot be special characters in the file name. You may also need to confirm that there are no special characters in the file path. Maybe it will help:)
