### ISSUE TITLE
Cannot Drag and Drop files in Logic Pro

### ISSUE THREAD

**Issue by monks-cat** [DamRsn/NeuralNote#89]
Thank you for this amazing application! 

When using logic, I could not drag and drop files into the plugin (.component version) , which I believe is the main point of it being a "plugin" as opposed to an individual standalone application. I saw this functionality in other DAWs in youtube videos, so I was hoping it could also work in logic, one of the main DAWs used on Macs. Sorry if I'm missing something! 

Appreciate all of your hard work

**Comment by DamRsn** [comment]
Hi,

Sorry for the late response. Unfortunately I think it has something to do with Logic Pro not allowing to drag audio regions as audio files into plugins. But you should be able to drag an audio file from the Finder to the plugin opened in Logic. 

I know it's not ideal but I don't know what's the way around for that. If someone has a clue please let me know.
