### ISSUE TITLE
Cannot open NeuralNote on a Mac (OS 

### ISSUE THREAD

**Issue by 20x25** [DamRsn/NeuralNote#90]
Hi 
I can't open Neural Note standalone app on a MacBook Pro (OS Ventura 13.6). I don't under stand why
best regards 
Christophe

**Comment by DamRsn** [comment]
Hi,

Do you see any error message? Or if you go to your `Privacy and Security` settings, do you see anything related to NeuralNote?

**Comment by 20x25** [comment]
The message says that it's impossible to open NeuralNote 
![Capture d’écran 2024-01-25 à 12 28 49](https://github.com/DamRsn/NeuralNote/assets/157700386/ed31084b-9356-4089-ae12-3c7af52590ac)

**Comment by 20x25** [comment]
and nothing happens in Privacy and security (there's nothing about NeurlaNote)

**Comment by 20x25** [comment]
(BTW, AU and VST3 work perfectly!)

**Comment by DamRsn** [comment]
If you haven't already tried, you can re-download the app, maybe the file is corrupted. 

What do you get if you click on the interrogation mark?

**Comment by 20x25** [comment]
there is no message when I click on the interrogation mark...

**Comment by 20x25** [comment]
I found the issue!!! the aZip unarchiver doesn't work! When I use unzip it works!!! thank you!
