### ISSUE TITLE
how does standalone connect to DAW?

### ISSUE THREAD

**Issue by fredphoesh** [DamRsn/NeuralNote#93]
Hi,
I've just installed this, thought i'd be able to spit out a MIDI file from the standalone app, now trying and failing to see how to connect to DAW... BTW my file is drums only... could this be why nothing is showing up?
Are there any instructions available?
Tx
Mark

**Comment by DamRsn** [comment]
Hi,

You should be able to export a MIDI file from the standalone app to any DAW, or any other app that accepts external file drag (for example File explorer or Finder). To do this, simply click and drag from the `Drag the midi file from here` banner to where you want to move the file (a midi track on your DAW for example).

NeuralNote does not support drums/percussion transcriptions, so yes that might be the reason why you don't get any notes in the transcription. 

Let me know if it still does not work for tonal instrument or a voice samples.

Hope this helps!

**Comment by fredphoesh** [comment]
Hi, thanks for letting me know... I did try an mp3 with audio just to have
a lookie see and it does indeed work... I'd used Google Gemini this morning
to ask what addons it could suggest to convert a drum pattern wav to midi
and it suggested neuralnote... be well, and thanks again for explaining.
I'm pasting an image here, not sure if it will publish:
[image: image.png]
Mark.

**Comment by fredphoesh** [comment]
here is what Gemini said:
![nn](https://github.com/DamRsn/NeuralNote/assets/5565996/a16f5310-caf5-41d8-9c2a-7fa7576ca0a9)
