### ISSUE TITLE
How to cleanup the MIDI file for transcription?

### ISSUE THREAD

**Issue by adrian-vogler** [DamRsn/NeuralNote#95]
First of all thank You for this app. It does a very good job of audio 2 midi. I use it on guitar tracks with good results in Cubase when I connect a guitar instrument (Ample guitar).

But I would like to get a human playable transcription out of it, too. So how can I separate the MIDI into different tracks for various instruments?

I use stemming to get voice and guitar separated.
But in recordings there are at least two guitars (lead and rythm) to separate.

How can I go on with NeuarlNotes results?

**Comment by DamRsn** [comment]
Hi,

Basic pitch will basically transcribe everything it detects. It was trained with single instrument clips, so it's good that you first separate voice and guitar. But when they are two guitars in the same track, it's hard to disentangle them. 

Unfortunately there's no tool to post process automatically the midi output from NeuralNote to make it cleaner, it is still a task that has to be done manually.
