### ISSUE TITLE
Support 44.1 kHz

### ISSUE THREAD

**Issue by mslinn** [DamRsn/NeuralNote#97]
The Windows standalone program only works at 48 kHz, perhaps the other published packages are the same in that regard, I do not know. 

Basic Pitch also supports 44.1 kHz, and all versions of NN should also support 44.1 kHz.

**Comment by DamRsn** [comment]
Hi,

NeuralNote should work at any standard sample rate. It might be your selected audio interface in the standalone app that forces you to use 48 kHz. I've seen that before on Windows.

Hope this helps.

**Comment by mslinn** [comment]
I think you misunderstand. The NN GUI provides a pull-down menu with only one value. Yesterday it only showed 48 kHz; today I only see 44.1 kHz; I am unclear why.

![image](https://github.com/DamRsn/NeuralNote/assets/485818/21a7275b-0db8-4cf4-bec3-c1fa9f15d2c0)

The Basic Pitch UI offers two values: 48 and 44.1 kHz.

**Comment by mslinn** [comment]
Aha! That solves the problem.

![image](https://github.com/DamRsn/NeuralNote/assets/485818/cec238a6-c5c7-4c51-9332-bc935b2abc85)

**Comment by mslinn** [comment]
Is it true that the above configuration of the audio device is not required for, and is independent of, the audio-to-midi conversion?
