### ISSUE TITLE
NeuralNote Review

### ISSUE THREAD

**Issue by mslinn** [DamRsn/NeuralNote#98]
```
Just a little review I wrote.
I hope you read it note for note.
Don't worry,
Be happy.
```

https://www.mslinn.com/av_studio/760-ai-midi.html

You are welcome to leave a comment here, or contact me directly.

**Comment by DamRsn** [comment]
Thanks for the review! It's great to have a comparison of the different audio-to-midi solutions available out there!

Few comments:
- See the other Github issues about the Windows sample rate locked at 48 kHz and the min note duration thing.
- I think the term `LLM` (Large Language Model) is used incorrectly in the article. BasicPitch is a tiny neural network with ~16,000 parameters, while LLM usually have tens of billions of parameters. And BP is not doing any language modelling. Regarding `AI-MIDI`, I don't know what kind of ML model they're using.

**Comment by mslinn** [comment]
I will edit the article to be more precise. Thank you for the feedback :)

**Comment by mslinn** [comment]
I noticed how very similar NeuralNote looks in comparison with Decent Sampler:

Is this because both are based on `eyalamirmusic/JUCECmakeRepoPrototype`?

![decent_sampler](https://github.com/DamRsn/NeuralNote/assets/485818/6b5e6c75-ae7e-470f-8ea7-ad898c967ac8)
